# Don't change this! Version used to track needed updates.
version = 1

[disabler]
disablerEnabled = true
disabledEnchantments = [
    "tombstone:blessing",
    "tombstone:curse_of_bones",
    "tombstone:decrepitude",
    "tombstone:frostbite",
    "tombstone:incurable_wounds",
    "tombstone:magic_siphon",
    "tombstone:plague_bringer",
    "tombstone:ruthless_strike",
    "tombstone:sanctified",
    "tombstone:soulbound",
    "tombstone:spectral_bite",
    "tombstone:spectral_conjurer"
]

[maxLevel]
modifyMaxLevels = false
maxLevels = [  ]
limitObtainableEnchantmentLevel = false
obtainableEnchantmentLevels = [  ]

[trades]
limitBookTradeLevel = false
bookTradeLevelLimit = 5
modifyEnchantedBookTradeUses = false
maxEnchantedBookTradeUses = 12
modifyEnchantedItemTradeUses = false
maxEnchantedItemTradeUses = 3
enchantedBookTradeRestockEnabled = true
enchantedItemTradeRestockEnabled = true

[enchantingTable]
enchantingTableEnabled = true
modifyMaxTablePower = false
maxTablePower = 15
modifyLapisCost = false
lapisCostFormula = "i+1"
modifyXpCost = false
xpCostFormula = "i+1"

[loot]
modifyEnchantWithLevelsMaxPower = false
enchantWithLevelsMaxPower = 50