[goggles]
enhancedInfo = true
hideStaticKineticInfo = true
betterStoreInfo = true
enableKineticEffect = false
preciseNumber = false
disableScreenGoggles = true
canRenderOnValueBox = false
extraItemTooltip = true
[gameMode]
enableGoggles = true
enableInSurvival = true
enableInCreative = true
enableInSpectator = true
enableInAdventure = true
[overlay]
renderItemOverlay = true
overlayOffsetX = 0
overlayOffsetY = 0
tooltipFlagType = "Default"
tooltipTheme = "Default"
useCustomColor = false
backgroundColor = 0
borderTopColor = 0
borderBottomColor = 0
[outliner]
renderAnalogBox = false
betterLine = true
delayRenderDuration = 20
outColor = 14532966
inColor = 8375776
rainbowDebug = false
[chainConveyor]
alwaysAllowRiding = true
preventFalling = false
enhancedConnection = false
cardBoardedYourself = true
[wrench]
fixRotationMenu = true
betterEncasedCogwheel = true
betterEncasedPipe = true
betterChassis = true
alwaysShowScrollValue = true
alwaysAllowRotating = true
leftClickFastDismantle = false
removeCooldown = true
enchancedRotationMenu = false
[misc]
removeMechanicalArmLimit = false
preventSelectionDiscard = true
infEditBoxLength = false
removeCardboardOverlay = true
removeNetheriteFirstPerson = false
allowDivingBoot = true
fixSchematicName = true
forcedBackend = false
nbtFix = false
showScrapContent = true
