version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fastitemframes = true
azurelib = true
everycomp = true
farmersdelight = true
eternal_starlight = true
create_mechanical_extruder = true
mcwbyg = true
lendersdelight = true
chimes = true
cataclysm = true
golemoverhaul = true
friendsandfoes = true
ecologics = true
starbunclemania = true
irons_spellbooks = true
stonezone = true
instrumentalmobs = true
ars_technica = true
hazennstuff = true
create_enchantment_industry = true
woodwevegot = true
the_bumblezone = true
amendments = true
mynethersdelight = true
fruitsdelight = true
ftbquests = true
lolmcv = true
relics = true
drill_drain = true
exposure = true
renether = true
enderscape = true
endersdelight = true
l2complements = true
supplementaries = true
apotheosis = true
createaddition = true
arsdelight = true
deeperdarker = true
chipped = true
endrem = true
sawmill = true
create = true
aquaculture = true
mythsandlegends = true
createcasing = true
lootr = true
rusticdelight = true
rottencreatures = true
create_deep_dark = true
biomeswevegone = true
transmog = true
hexerei = true
visualworkbench = true
tombstone = true
crystal_chronicles = true
minecraft = true
fdlib = true
create_dragons_plus = true
alshanex_familiars = true
mowziesmobs = true
create_connected = true
iceandfire = true
fdbosses = true
apothic_enchanting = true
mcwfurnitures = true
refinedstorage = true
creeperoverhaul = true
travelersbackpack = true
sophisticatedstorage = true
ars_elemental = true
aquaculturedelight = true
endermanoverhaul = true
waystones = true
bosses_of_mass_destruction = true
gag = true
ars_nouveau = true
forbidden_arcanus = true
mobs_of_mythology = true
illagerinvasion = true
expandeddelight = true
create_integrated_farming = true
littlejoys = true
