["Sword Mod Configs"]
#How many blocks in each direction from the dead player should the heal affect
healRadius = 100
#Should the heal amount depend on how many nearby players there are?
multiplayerMode = true
#In Singleplayer Mode what percentage of maxhealth should a mob heal?
singleplayerHealPercentage = 50
