#Options related to player's death
[player_death]
#The time in minutes before a grave is unlocked to anyone [-1..MAX|default:-1|disabled:-1]
# Default: -1
# Range: > -1
decay_time = -1
#Experience lost on death [0..100|default:95]
# Default: 95
# Range: 0 ~ 100
xp_loss_on_death = 50
#The duration of the Ghostly Shape effect in seconds [0..MAX|default:120]
# Default: 120
# Range: > 0
ghostly_shape_duration = 120

#Allows to customize or disable the enchantments
[enchantments]
#Allows Soulbound at enchanting table [false/true|default:false]
soulbound_enchanting_table = false
#Allows Spectral Bite at enchanting table [false/true|default:false]
spectral_bite_enchanting_table = false
#Allows Magic Siphon at enchanting table [false/true|default:false]
magic_siphon_enchanting_table = false
#Allows Plague Bringer at enchanting table [false/true|default:false]
plague_bringer_enchanting_table = false
#Allows Curse of Bones at enchanting table [false/true|default:false]
curse_of_bones_enchanting_table = false
#Allows Blessing at enchanting table [false/true|default:false]
blessing_enchanting_table = false
#Allows Frostbite at enchanting table [false/true|default:false]
frostbite_enchanting_table = false
#Allows Spectral Conjurer at enchanting table [false/true|default:false]
spectral_conjurer_enchanting_table = false
#Allows Incurable Wounds at enchanting table [false/true|default:false]
incurable_wounds_enchanting_table = false
#Allows Decrepitude at enchanting table [false/true|default:false]
decrepitude_enchanting_table = false
#Allows Sanctified at enchanting table [false/true|default:false]
sanctified_enchanting_table = false
#Allows Ruthless Strike at enchanting table [false/true|default:false]
ruthless_strike_enchanting_table = false

#Allows to customize or disable the potions
[potions]
#Allows Earthly Garden [false/true|default:true]
allow_earthly_garden = false
#Allows Bait [false/true|default:true]
allow_bait = false
#Allows Frostbite [false/true|default:true]
allow_frostbite = false
#Allows Darkness [false/true|default:true]
allow_darkness = false
#Allows Discretion [false/true|default:true]
allow_discretion = false
#Allows Restoration [false/true|default:true]
allow_restoration = false
#Allows Weaver Walk [false/true|default:true]
allow_weaver_walk = false
#Allows Giant Strength [false/true|default:true]
allow_giant_strength = false
#Allows Little World [false/true|default:true]
allow_little_world = false

#For settings related to magic items
[magic_item]
#Prevents to craft Enchanted Grave Key [false/true|default:false]
disable_enchanted_grave_key_recipe = false
#Scroll duration [1200..120000|default:12000]
# Default: 12000
# Range: 1200 ~ 120000
scroll_duration = 12000
#Defines experience lost when storing experience in a Scroll of Knowledge
# Default: 0
# Range: 0 ~ 90
scroll_of_knowledge_loss = 0
#Cooldown in second after using a tablet [60..1200|default:300]
# Default: 300
# Range: 60 ~ 1200
tablet_cooldown = 300
#Maximum level for Magic Scrolls [0..255|default:4]
# Default: 4
# Range: 0 ~ 255
level_max_magic_scrolls = 4
#Chance for players to obtain an enchanted Grave's Key on death (-1 disables the Perk Jailer) [-1..100|default:0]
# Default: 0
# Range: -1 ~ 100
chance_enchanted_grave_key = 0
#The cooldown in minutes to reset the perks with the Book of Oblivion [20..1440|default:120]
# Default: 120
# Range: 20 ~ 1440
cooldown_reset_perk = 120

#For settings related to decorative tombs and magic items
[decorative_grave]
#The cooldown in minutes to pray with the Ankh [1..60|default:60]
# Default: 60
# Range: 1 ~ 60
prayer_cooldown = 60

#Allows to disable some magic items
[allowedMagicItems]
#Voodoo Poppet [false/true|default:true]
allow_voodoo_poppet = false
#Receptacle of Familiar [false/true|default:true]
allow_receptacle_of_familiar = false
#Book of Disenchantment [false/true|default:true]
allow_book_of_disenchantment = false
#Scroll of Preservation [false/true|default:true]
allow_scroll_of_preservation = false
#Grave's Key [false/true|default:true]
allow_grave_key = true
#Scroll of Knowledge [false/true|default:true]
allow_scroll_of_knowledge = false
#Tablet of Recall [false/true|default:true]
allow_tablet_of_recall = true
#Tablet of Home [false/true|default:true]
allow_tablet_of_home = false
#Tablet of Assistance [false/true|default:true]
allow_tablet_of_assistance = true
#Tablet of Cupidity [false/true|default:true]
allow_tablet_of_cupidity = false
#Tablet of Guard [false/true|default:true]
allow_tablet_of_guard = false
#Scroll of Unstable Intangibility [false/true|default:true]
allow_scroll_of_unstable_intangibility = false
#Scroll of Feather Fall [false/true|default:true]
allow_scroll_of_feather_fall = false
#Scroll of Purification [false/true|default:true]
allow_scroll_of_purification = false
#Scroll of True Sight [false/true|default:true]
allow_scroll_of_true_sight = false
#Lost Tablet [false/true|default:true]
allow_lost_tablet = true
#Scroll of Reach [false/true|default:true]
allow_scroll_of_reach = false
#Scroll of Lightning Resistance [false/true|default:true]
allow_scroll_of_lightning_resistance = false
#Scroll of Frost Resistance [false/true|default:true]
allow_scroll_of_frost_resistance = false
#Scroll of Aquatic Life [false/true|default:true]
allow_scroll_of_aquatic_life = false
#Scroll of Mercy [false/true|default:true]
allow_scroll_of_mercy = false
#Scroll of Projectile Reflection [false/true|default:true]
allow_scroll_of_projectile_reflection = false
#Dust of Vanishing [false/true|default:true]
allow_dust_of_vanishing = false
#Dust of Frost [false/true|default:true]
allow_dust_of_frost = false
#Book of Recycling [false/true|default:true]
allow_book_of_recycling = false
#Book of Repairing [false/true|default:true]
allow_book_of_repairing = false
#Book of Magic Impregnation [false/true|default:true]
allow_book_of_magic_impregnation = false
#Book of Scribe [false/true|default:true]
allow_book_of_scribe = false
#Book of Soulbound [false/true|default:true]
allow_book_of_soulbound = false
#Book of Oblivion [false/true|default:true]
allow_book_of_oblivion = true
#Smoke Ball [false/true|default:true]
allow_smoke_ball = false
#Seeker Rod [false/true|default:true]
allow_seeker_rod = true
#Christmas Hat [false/true|default:true]
allow_christmas_hat = true
#Bag of Seeds [false/true|default:true]
allow_bag_of_seeds = true
#Magic Scroll [false/true|default:true]
allow_magic_scroll = false
#Gemstone of Familiar [false/true|default:true]
allow_gemstone_of_familiar = false
#Gemstone of Merchant [false/true|default:true]
allow_gemstone_of_merchant = false
#Gemstone of Prayer [false/true|default:true]
allow_gemstone_of_prayer = false
#Gemstone of Guardian [false/true|default:true]
allow_gemstone_of_guardian = false
