#The delay in ticks before the spell is cast
# Default: 10
# Range: > 0
delay = 10
#The cost of casting this spell
# Default: 40
# Range: > 0
cost = 40
#The amount of damage dealt by the spell
# Default: 10.0
# Range: 1.0 ~ 2.147483647E9
damage = 10.0
