#The delay in ticks before the spell is cast
# Default: 10
# Range: > 0
delay = 10
#The cost of casting this spell
# Default: 20
# Range: > 0
cost = 20
#Cooldown for this prayer spell
# Default: 0
# Range: > 21000
cooldown = 21000
#Base reputation gained from this prayer spell
# Default: 8
# Range: > 0
base_reputation = 8
#Altar Power multiplier for reputation gained with this prayer spell
# Default: 1.25
# Range: 0.0 ~ 1.7976931348623157E308
power_multiplier = 1.25
